### ISSUE TITLE
Is it possible to mute only minimized apps?

### ISSUE THREAD

**Issue by Rik-Kirtaniya** [nefares/Background-Muter#13]
Use case scenario: I am running two windows A and B side by side, A is playing audio but I need to click on B occasionally, which causes A to turn into a non-active window and thus get muted.

Is it possible to make it so that the window gets muted _**only**_ when minimized to taskbar but not when it is merely clicked outside of and made non-active?

**Comment by nefares** [comment]
Added as a feature request. This can be implemented as a global setting, so it will affect the muting behavior overall and not for specific windows.

**Comment by lamrongol** [comment]
I also want this feature and sent pull request.
https://github.com/nefares/Background-Muter/pull/17

**Comment by nefares** [comment]
Please confirm the closure of this issue

**Comment by Rik-Kirtaniya** [comment]
@nefares Works perfectly according to my testing. Thanks a lot to both you and @lamrongol for making this feature.

(Now I can have my visual novels running in the background without having to close them every time I want to do something else. :D)

**Comment by lamrongol** [comment]
I confirmed this works correctly at the moment.

**Comment by lamrongol** [comment]
Hmm... I restarted Windows and this doesn't work before once changing config.

**Comment by nefares** [comment]
Thanks for the positive feedback!

@lamrongol  will close this for now since the feature is implemented. Can you create a separate issue for the bug you encountered.
