### ISSUE TITLE
Windows defender flags as virus

### ISSUE THREAD

**Issue by zhaDeth** [nefares/Background-Muter#2]
Windows defender won't let me use the app, says it's some virus, sadly I can't compile it myself

**Comment by nefares** [comment]
Thanks for reporting this. Seems to be an issue with the installer being flagged. Will send the original installer to microsoft for removal of the false positive.

In the mean time I have removed the binary file and uploaded a ZIP containing a portable version of the tool. Simply extract somewhere and run the executable (https://github.com/nefares/Background-Muter/releases/download/v1.0.0.1/WinBGMuter.zip)

Let me know if you still have an issue with the new file.

**Comment by zhaDeth** [comment]
Seems to work fine now thanks !

**Comment by nefares** [comment]
In case virus alerts comes up again try updating windows signature files:
![image](https://user-images.githubusercontent.com/8545128/168913912-a7cd78c6-950d-4e27-bdaf-82365f2d74bc.png)
