### ISSUE TITLE
Inclusivity vs. Exclusivity

### ISSUE THREAD

**Issue by lakecityransom** [nefares/Background-Muter#27]
It would be nice if there was an option that assumes nothing should mute unless you add it to the list. The frustrating thing about how it is now is I have to keep going back and adding exceptions as I open more and more programs and realize it is muting them. I am going to have a hugggge list of ever-growing exceptions.

The way this works right now is it assumes you want to mute everything but the 1 current program in the foreground. I am guessing a lot of people just have one or a few programs they need this to mute when out of focus. A lot of programs do handle muting properly when out of focus, but some do not have an option. Games can be a big culprit of this when borderless fullscreen.

**Comment by nefares** [comment]
Noted. This seems however to be the same as #16. Let me know if there are additional points otherwise will close this issue (since #16 will be kept open)

**Comment by lakecityransom** [comment]
oh my bad
